### ISSUE TITLE
Roadmap for moving vz out of experimental

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#1610]
- [X] Basic tests #1511
- [x] https://github.com/lima-vm/lima/issues/1611
- [X] https://github.com/lima-vm/lima/issues/1577
- [x] #1333
- [ ] #1609
- [x] https://github.com/lima-vm/lima/issues/1957
We can also consider making vz default after moving it out of experimental

**Comment by ningziwen** [comment]
This [issue](https://github.com/lima-vm/lima/issues/1609) seems also significant although it is hard to reproduce and root cause.

**Comment by AkihiroSuda** [comment]
Merged:
- https://github.com/lima-vm/lima/pull/1951
