### ISSUE TITLE
Promote Lima from CNCF Sandbox to Incubation

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/lima#2068]
I think we are getting close to satisfy the requirements for the Incubating Stage:

https://github.com/cncf/toc/blob/main/process/graduation_criteria.md#incubating-stage

> ### Incubating Stage
> 
> *Note: The incubation level is the point at which we expect to perform full [due diligence](https://github.com/cncf/toc/blob/main/process/due-diligence-guidelines.md) on projects.*
> 
> To be accepted to incubating stage, a project must meet the sandbox stage requirements plus:
> 
>  * Document that it is being used successfully in production by at least three independent direct adopters which, in the TOC’s judgement, are of adequate quality and scope. For the definition of an adopter, see https://github.com/cncf/toc/blob/main/FAQ.md#what-is-the-definition-of-an-adopter.
> 
>  * Have a healthy number of committers. A committer is defined as someone with the commit bit; i.e., someone who can accept contributions to some or all of the project.
>  * Demonstrate a substantial ongoing flow of commits and merged contributions.
>  * Since these metrics can vary significantly depending on the type, scope and size of a project, the TOC has final judgement over the level of activity that is adequate to meet these criteria
>  * A clear versioning scheme.
>  * Clearly documented security processes explaining how to report security issues to the project, and describing how the project provides updated releases or patches to resolve security vulnerabilities 
>  * Specifications must have at least one public reference implementation.
> 

- - -
## TODOs

- [x] Complete [OpenSSF Best Practices](https://www.bestpractices.dev/en/projects/6505)
  - [x]  https://github.com/lima-vm/lima/pull/2385

- [X] Submit [Security Self-Assessment](https://github.com/cncf/tag-security/blob/main/assessments/guide/self-assessment.md) to <https://github.com/cncf/tag-security/tree/main/assessments/projects> 
   - https://github.com/cncf/tag-security/pull/1264

- [X] Submit an incubation application to <https://github.com/cncf/toc/issues>
  -  https://github.com/cncf/toc/issues/1348

- [x] Wait for approval

**Comment by AkihiroSuda** [comment]
Some document templates might be going to change:
- https://github.com/cncf/toc/pull/1236

**Comment by AkihiroSuda** [comment]
They updated the template:
https://github.com/cncf/toc/blob/main/.github/ISSUE_TEMPLATE/template-incubation-application.md

**Comment by AkihiroSuda** [comment]
- https://github.com/lima-vm/lima/pull/2353

**Comment by AkihiroSuda** [comment]
- https://github.com/cncf/tag-security/pull/1264

**Comment by AkihiroSuda** [comment]
- https://github.com/cncf/toc/issues/1348

**Comment by AkihiroSuda** [comment]
Due diligence:
- https://github.com/cncf/toc/pull/1881
