### ISSUE TITLE
Apply for CNCF Sandbox status

### ISSUE THREAD

**Issue by jandubois** [lima-vm/lima#947]
**EDIT** (by @AkihiroSuda)

The submission is expected to be reviewed by the CNCF TOC on Sep 13, 2022.

- - -
CNCF would be a good fit for a vendor-neutral project owner. It also provides the following perks:

* [Services for CNCF Projects](https://www.cncf.io/services-for-projects/)
* [KubeCon & CloudNativeCon benefits](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/program/project-benefits/#project-benefits)

The [CNCF Proposal Process](https://github.com/cncf/toc/blob/main/process/project_proposals.md) requires us to fill out an [Application](https://docs.google.com/forms/d/1bJhG1MuM981uQXcnBMv4Mj9yfV5_q5Kwk3qhBCLa_5A/viewform?edit_requested=true) for inclusion in the [Sandbox](https://github.com/cncf/toc/blob/main/process/sandbox.md) (* is required):

* [X] Email*
suda.kyoto@gmail.com and jan@jandubois.com

* [X] Project Name*
Lima

* [X] Project Description*
Linux virtual machines, made for running containerd and Kubernetes on macOS, with automatic host file system sharing and port forwarding.
Aside from macOS, Lima is known to work on Linux and NetBSD hosts as well. Windows port is in progress too.
Lima already has received 8.7k stars on GitHub.

* [X] Code repository (URL)*
https://github.com/lima-vm/lima and other repositories in the [lima-vm](https://github.com/lima-vm) org.

* [X] Website (URL)
Lima has no website besides the Github repo `README.md` and the `docs` folder.

* [X] Project Roadmap (URL)*
https://github.com/lima-vm/lima/blob/master/ROADMAP.md

* [X] Why do you want to contribute your project to the CNCF? What would you like to get out of being part of the CNCF?*
We are seeking a vendor-neutral home for the project, to take ownership of the project assets, and also to provide legal protection, if that ever becomes necessary. We are also interested in a refresh of our logo and getting a #lima channel on the CNCF Slack instance.

* [x] Code of conduct (URL)*
Lima follows the CNCF Code of Conduct: https://github.com/lima-vm/.github/blob/main/CODE_OF_CONDUCT.md

* [X] I understand that if accepted, the project will be required to follow the [CNCF IP Policy](https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy)*
I accept the CNCF IP Policy

* [X] I understand that I am donating all project trademarks and accounts to the CNCF*
I Accept

* [X] Please explain how your project is aligned with the cloud native computing ecosystem.*
Lima helps developing cloud native apps by allowing running containerd (including nerdctl, a Docker-compatible CLI) and Kubernetes on laptops.

* [x] Please list similar projects in the CNCF or elsewhere*
[Multipass](https://multipass.run), [WSL2](https://docs.microsoft.com/en-us/windows/wsl/install), [vagrant](https://www.vagrantup.com), [docker-machine](https://github.com/docker/machine)

* [x] Guidelines/help for project contributors (URL)*
https://github.com/lima-vm/.github/blob/main/CONTRIBUTING.md

* [X] Explanation of alignment/overlap with existing CNCF projects (optional)
The scope of Lima overlaps with minikube (Kubernetes SIG-cluster-lifecycle project) for running Kubernetes, but Lima also focuses on seamlessly running non-Kubernetes applications including containerd/nerdctl.

* [X] Existing project overview presentation (optional)
https://github.com/lima-vm/lima/blob/master/docs/talks.md

* [X] Maintainers file (optional)
https://github.com/lima-vm/lima/blob/master/MAINTAINERS.md

* [X] Link to project artwork: (optional)
https://github.com/lima-vm/lima/blob/master/docs/images/lima-logo-01.svg

**Comment by afbjorklund** [comment]
Maybe add docker-machine and vagrant as similar software ? Let me know if you require more details about minikube, compared with lima that is

**Comment by afbjorklund** [comment]
Possibly use the new artwork (and logo), when creating the new Lima website ?

**Comment by jandubois** [comment]
> Maybe add docker-machine and vagrant as similar software ? Let me know if you require more details about minikube, compared with lima that is

I'll add them to the list above; not sure how much detail we need; I think the whole application becomes a single row in a spreadsheet for review by the TOC, so it may need to be brief. I'll try to find out more.

> Possibly use the new artwork (and logo), when creating the new Lima website ?

Getting new artwork is one of the perks of being admitted to the CNCF: https://www.cncf.io/services-for-projects/#design-and-aesthetics:

> CNCF offers graphic design resources for all projects, provided primarily by our in-house design team. When new projects enter the foundation, they receive a new logo, website refresh if they wish, or an enhancement of their existing aesthetic.

So we can try to get them to create a Lima bean logo for us. 😄

**Comment by afbjorklund** [comment]
> So we can try to get them to create a Lima bean logo for us.

I liked the proposed logo, but maybe that was just me...

**Comment by jandubois** [comment]
> I liked the proposed icon and logo, but maybe that was just me...

Let's keep the artwork discussion in #268 please!

**Comment by mattfarina** [comment]
> should we use personal email addresses instead?

It doesn't matter.

> made for running containerd and Kubernetes on macOS

There's some support for Linux. Should that be mentioned, too?

> https://github.com/lima-vm/lima and other repositories in the [lima-vm](https://github.com/lima-vm) org.

Will this include everything? Even things like https://github.com/lima-vm/sshwebdav

**Comment by AkihiroSuda** [comment]
> > made for running containerd and Kubernetes on macOS
> 
> There's some support for Linux. Should that be mentioned, too?

Added `Aside from macOS, Lima is known to work on Linux and NetBSD hosts as well. Windows port is in progress too.`


> > https://github.com/lima-vm/lima and other repositories in the [lima-vm](https://github.com/lima-vm) org.
> 
> Will this include everything? Even things like https://github.com/lima-vm/sshwebdav

Yes, just like https://github.com/containerd contains everything

**Comment by AkihiroSuda** [comment]
Fulfilled the [form](https://docs.google.com/forms/d/1bJhG1MuM981uQXcnBMv4Mj9yfV5_q5Kwk3qhBCLa_5A/viewform?edit_requested=true), but the form accepts only single email address (mine)

**Comment by AkihiroSuda** [comment]
Accepted 🎉 
Thank you all contributors for making this possible!

- https://github.com/cncf/toc/issues/924
